CREATE TABLE manufacturers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP,
    valid BOOLEAN NOT NULL,

    name varchar(100),
    description varchar(255),

    CONSTRAINT pk_manufacturer PRIMARY KEY (id)
);