CREATE TABLE manufacturers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP,
    modifier_user varchar(255),
    valid BOOLEAN NOT NULL DEFAULT TRUE,

    name varchar(100),
    description varchar(255),

    CONSTRAINT pk_manufacturer PRIMARY KEY (id)
);